[mongo]
localhost

[catalogue]
localhost

[redis]
localhost

[cart]
localhost

[user]
user-dev.happielearning.com

[mysql]
mysql-dev.happielearning.com

[shipping]
shipping-dev.happielearning.com

[rabbitmq]
rabbitmq-dev.happielearning.com

[payment]
payment-dev.happielearning.com

[frontend]
frontend-dev.happielearning.com

[local]
localhost